Feature/quiz functionality and ui/arc 759
ted3x/QuizApp pull request #2
Opened 2020-11-22 13:31 UTC by ted3x

2020-11-22 19:35 UTC, DavitSoitashviliSpace requested changes

2020-11-22 19:35 UTC, DavitSoitashviliSpace commented on app/src/main/java/com/c0d3in3/quizapp/view/quiz_testing/adapter/AnswersAdapter.kt
> +
I think, It would be better to get model from callback (selectAnswer) and work with this model rather than work with index.

2020-11-22 19:35 UTC, DavitSoitashviliSpace commented on app/src/main/java/com/c0d3in3/quizapp/view/welcome/WelcomeFragment.kt
> +            else{
if you are using Toast message, you can create function and set context and message as parameters.

2020-11-22 20:36 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/quiz_testing/adapter/AnswersAdapter.kt
> +
I use answers in adapters, not models. I can't pass them in adapter, also I have model in ViewModel so this structure works well for me.

2020-11-23 08:07 UTC, Edna001 commented on app/src/main/java/com/c0d3in3/quizapp/view/welcome/WelcomeFragment.kt
> +            else{
++

2020-11-24 08:42 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/welcome/WelcomeFragment.kt
> +            else{
Changed

2020-11-25 13:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/shared_preferences/SharedPreferencesHandler.kt
> +            PREFERENCE_FILE_KEY, Context.MODE_PRIVATE)
It's the name of the preference file

2020-11-25 13:29 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/quiz_dashboard/QuizDashboard.kt
> +                val bundle = bundleOf(BUNDLE_MODEL_KEY to quizModel)
I think BUNDLE_MODEL_KEY is identifier of bundle's key, not text value. So it has to be constant variable.

2020-11-25 13:30 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/quiz_testing/QuizTestingViewModel.kt
> +    fun gotoNextQuestion(){
Sure :D changed

2020-11-25 13:31 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/quiz_dashboard/QuizDashboard.kt
> +        viewModel.welcomeMessage.observe(viewLifecycleOwner, Observer {
Changed

2020-11-25 13:41 UTC, anarusadzeSpace approved these changes

2020-11-26 07:34 UTC, Edna001 approved these changes

2020-11-26 16:12 UTC, anarusadzeSpace commented on app/src/main/java/com/c0d3in3/quizapp/base/BaseFragment.kt
> +        if (viewModelToken != null) ViewModelProvider(this)[viewModelToken!!] else null
u can also try elvis operator here. it will be like:
private fun providerViewModel() = ViewModelProvider(this){viewModelToken!!] ?: null

2020-11-26 16:12 UTC, anarusadzeSpace commented on app/src/main/java/com/c0d3in3/quizapp/view/welcome/WelcomeFragment.kt
>              if(name.isBlank()) showShortToast(requireActivity(), getString(R.string.name_field_is_empty))
requireContext() will be better than requireActivity(), i think, otherwise it will be activity based . i'm not sure about that, tu vcdebi mitxari ;d

2020-11-26 19:24 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/base/BaseFragment.kt
> +        if (viewModelToken != null) ViewModelProvider(this)[viewModelToken!!] else null
I don't think that will work, we have to check viewmodeltoken if it's null or not. if we dont check it, we might get nullpointerException.

2020-11-26 19:28 UTC, ted3x commented on app/src/main/java/com/c0d3in3/quizapp/view/welcome/WelcomeFragment.kt
>              if(name.isBlank()) showShortToast(requireActivity(), getString(R.string.name_field_is_empty))
You are right

2020-11-27 17:15 UTC, Edna001 approved these changes

2020-11-30 09:42 UTC, merged